### ISSUE TITLE
How Can We Calculate and Include Confidence Scores during inference?

### ISSUE THREAD

**Issue by Shohruh72** [Tobias-Fischer/rt_gene#125]
Could you provide guidance or implement a feature to calculate and include confidence scores in the inference output? This would help users better assess the accuracy and reliability of the gaze predictions.

**Comment by Tobias-Fischer** [comment]
Unfortunately, that's not trivial and a research topic on its own. You could try strategies such as ["Simple and Scalable Predictive Uncertainty Estimation using Deep Ensembles"](https://proceedings.neurips.cc/paper_files/paper/2017/file/9ef2ed4b7fd2c810847ffa5fa85bce38-Paper.pdf) (and many works since) to obtain uncertainties in the predictions. That said, confidence scores are outside the scope of this work.
