### ISSUE TITLE
no visual output after estimate gaze launch

### ISSUE THREAD

**Issue by anilrgukt** [Tobias-Fischer/rt_gene#41]
Hi, 

Once I run roslaunch rt_gene estimate_gaze.launch, I do not see any visual GUI showing the real time video overlaid with gaze vector. The images from the webcam are not even saved anywhere. 

All I see is this form of output on the terminal, 

Time diff: -3.10000000114e-08
Time now: 1570652893.51 message color: 1570652893.47 diff: 0.0460674762726
est_gaze_c: [ 0.05357103 -0.04007208]
Face Detector Frequency: 72.17Hz for 1 Faces
Elapsed after detecting transformed_landmarks: 0.0429921150208
New get_eye_image time: 0.000105142593384
Head Rotation from last frame: 0.00
Translation based on landmarks [ 0.61903054 -0.0703548  -0.02048527]
Elapsed total: 0.0445210933685

I am new to ROS, am I doing something wrong?

Thanks,
Anil

**Comment by Tobias-Fischer** [comment]
Hi Anil,
Thank you for your interest in our work! Good news is that the pipeline itself seems to work nicely. 

All you need to do is now visualizing the results:
Instead of running `roslaunch rt_gene estimate_gaze.launch`, please run `roslaunch rt_gene estimate_gaze.launch start_rviz:=True` which will start [rviz](http://wiki.ros.org/rviz). Please check the rviz tutorial to see how to change the images that are displayed. You can display 1) the webcam image, 2) the head pose image and 3) the eye images by choosing the different image topics.

If you want to save the images, you can use the [image_saver tool](http://wiki.ros.org/image_view#image_view.2BAC8-diamondback.image_saver).

Finally, keep in mind that there is also a (beta) standalone version of RT-GENE that does not need ROS. It is currently in the [modularised branch](https://github.com/Tobias-Fischer/rt_gene/tree/modularised).

Best, Tobias
