### ISSUE TITLE
reproduce

### ISSUE THREAD

**Issue by FigaroK** [Tobias-Fischer/rt_gene#46]
Hi, I ran your model training code with only changing the path. And I get following results:
Ensemble: 13.480204036924533 +- 3.772117425419047
Model 0: 15.14554381498352 +- 3.4026110207019453
Model 1: 14.49058686821486 +- 3.9057199613231455
Model 2: 13.60103630178998 +- 3.4098169707825843
Model 3: 14.496607138990932 +- 3.3971626371824732
Ensemble: 12.86649487961544 +- 3.6739599920738577
Model 0: 13.41469958155073 +- 3.516076889661513
Model 1: 13.237533686031147 +- 3.5218109462077685
Model 2: 13.376636419685994 +- 3.341763248689219
Model 3: 13.861938083633717 +- 3.30115446948625
Ensemble: 12.639686620568382 +- 3.6341994290148607
Model 0: 13.336198507628263 +- 3.2624630095315488
Model 1: 13.110821038670409 +- 3.4787565847257684
Model 2: 13.355155726032125 +- 3.0450093915309906
Model 3: 13.533675092731762 +- 3.055964720850351
Ensemble: 13.048184325211764 +- 3.711550885325419
Model 0: 13.621509926156996 +- 3.2997626846039445
Model 1: 13.280787940634553 +- 3.5138811741676848
Model 2: 13.611282873524203 +- 3.4179222462072456
Model 3: 13.632872017170953 +- 3.4504936315324413

Is this a roughly correct result?   Your paper reported the within-dataset result of rt-gene is 7.7 degrees. what did i ignore?

**Comment by ngageorange** [comment]
Hi,
There's been significant developments on the repo since the paper and the model hasn't been retrained. We now use a different face detector and a face landmark extractor, the latter specifically affects performance as the eye patches extracted aren't the same.

If you checkout the repository from the first commit, you'll be able to recreate the results of the paper.

We're in the process of retraining the gaze estimation network for the new developments - keep an eye out!

**Comment by FigaroK** [comment]
Hi, 
The code I used is exactly at the first commit (git log id: f457c1b). I got the results of 3-fold cross validation as above, and it seems far from 7.7 degrees. Could you provide some help?  My tensofrflow is 1.5.0 and keras is 2.1.4   .

**Comment by ngageorange** [comment]
Sorry for the delay in writing back - I've managed to re-create RT-GENE in pytorch; have a look at the `pytorch_training` branch.
The training there regularly goes down to 7 +/- 2 degrees within 3 epochs
