### ISSUE TITLE
Attribute error 

### ISSUE THREAD

**Issue by digbose92** [Tobias-Fischer/rt_gene#58]
When I am running the standalone gaze estimation script on an image , I am getting the following error : AttributeError: 'TrackedSubject' object has no attribute 'marks'. Does it mean the landmarks are not getting detected in that image ?

**Comment by ngageorange** [comment]
Hi @digbose92 ,

You're probably running off master right? This is related to a recent pull request where the code now publishes all pipeline predictions as ros messages. This particular bug was recently fixed but more discussions are being had on #54 .

I would highly suggest running off one of the releases rather than edge code if you'd like stability.

**Comment by Tobias-Fischer** [comment]
Hi @digbose92, could you please try again after pulling the latest changes?

Best, Tobi

**Comment by digbose92** [comment]
Hi @Tobias-Fischer , I ran after pulling the latest changes. It ran without any problems. Thanks :)
