### ISSUE TITLE
Error when running estimate_gaze_standalone

### ISSUE THREAD

**Issue by kchen003** [Tobias-Fischer/rt_gene#80]
I've been trying to run the standalone file for the last few days, but I'm currently getting errors when the environment is all configured.

After I run that python2 estimate_gaze_standalone.py samples_gaze

it reports an error as follows:

 

Loading networks

Using device cuda:0 for face detection

Trackback(most recent call last):

File "estimate_gaze_standalone.py", line 182, in <module>

gaze_estimator = GazeEstimator("/gpu:0", args.models)

TypeError: __new__() takes exactly 4 arguments(3 given)

 

 

It looks like I am just missing one argument when calling GazeEstimator.

My current configuration is Nvidia driver 450.57 CUDA 9.0 cudnn 7.3. 

I'm not quite sure why this error is occurring, so hopefully, you can give me some guidance.

**Comment by Tobias-Fischer** [comment]
Hi @kchen003,
Are you using the latest version of RT-GENE? Could you please provide the output of `git status` and `git rev-parse HEAD`? The `__init__` method takes 3 arguments, so I am not sure why it reports that it takes 4 arguments (see https://github.com/Tobias-Fischer/rt_gene/blob/master/rt_gene/src/rt_gene/estimate_gaze_tensorflow.py#L12 where it's easy to see that 3 arguments [including `self`] should be provided).

**Comment by kchen003** [comment]
I re-downloaded the latest version of rt_gene, and since I'm using python 2.7, I modified the estimate_gaze_base.py file. from abc import ABCMeta, in class GazeEstimatorBase(ABCMeta), and I do see the There are three arguments in estimate_gaze_tensorflow.py, but the error is in __new__(), and I see no static methods defined in the class. I'm not quite sure why this error is occurring at the moment.

**Comment by Tobias-Fischer** [comment]
Please post the outputs from the commands above, and additionally the output of `git diff`.

**Comment by Tobias-Fischer** [comment]
Just realized that "ABC" is not availably in python2.7; sorry for that. Please get the latest version of the code, this should work. If not, please reopen this issue.

/cc @ahmed-alhindawi

**Comment by kchen003** [comment]
Thank you so much for your help, this problem has been solved. However, I am currently still getting an error after downloading all the resources in the model_nets folder. 

**Traceback(most recent call last):
  File "estimate_gaze_standalone.py", line 182, in <module>
    gaze_estimator = GazeEstimator("/gup:0", args.models)
  File "/home/kchen/rt_gene/rt_gene/src/rt_gene/estimate_gaze_tensorflow.py", line 16, in __init__
    tf.compat.v1.disable_eager_execution()
AttributeError: 'module' object has no attribute 'v1'
Exception AttributeError: "'GazeEstimator' object has no attribute 'sess'" in <bound method GazeEstimator.__del__  of <rt_gene.estimate_gaze_tensorflow.GazeEstimator object at 0*7f34c500a810>>  ignored**

AttributeError is usually because of the .pyc file of the source file. Should I delete the .pyc file of the estimate_gaze_tensorflow?
I think the problem with GazeEstimator.__del__ may still be due to the python version.

**Comment by Tobias-Fischer** [comment]
What's the output of `print(tf.__version__)`? Also there is a typo gup instead of gpu in your code. Do you modify anything in the code? Again please provide the output of the git commands above otherwise it is very hard to remotely debug.

**Comment by kchen003** [comment]
Very sorry, typos can be ignored. I didn't change anything in the project, and the current version of my TensorFlow is 1.11.0
I first export PYTHONPATH=$HOME/rt_gene/rt_gene/src
Then in the rt_gene_standalone folder python2 estimate_gaze_standalone.py samples_gaze

**Comment by Tobias-Fischer** [comment]
You need at least tensorflow 1.14, please upgrade it.

**Comment by Tobias-Fischer** [comment]
Alternatively go back to https://github.com/Tobias-Fischer/rt_gene/releases/tag/v2.2 but I wouldn't recommend doing so and would not provide any support either.

**Comment by kchen003** [comment]
Thank you very much for your help, my project is up and running. But at the moment I'm still familiar with the logic and structure of the whole project. I'm only running as a standalone, but what do I need to do if I need to retrieve the eye movement data I've acquired? It's not just about outputting images. I tried to add publisher to the __init__ of esitimate_gaze, self.coords=rospy.Publisher("/subjects/coords", String, queue_size=1).
But I'm not sure where to get the data from the rospy.Subscriber that was put in before it was fetched. I haven't understand the logic for the whole project yet, and I don't know where the main function is.

**Comment by Tobias-Fischer** [comment]
Hi,
I am a little confused by your description. You first say that you use the standalone version (i.e. without ROS), but later talk about ROS publishers. Which of the two are you using?

In the standalone version, you can get the head pose and gaze estimates [here](https://github.com/Tobias-Fischer/rt_gene/blob/dea26ee5882340fb54202002c450f16c1b85cf59/rt_gene_standalone/estimate_gaze_standalone.py#L107). Note that you may get multiple estimates if there are multiple people in the image, that's why there is a for loop.

For ROS, you have two options:
- Either use a TF Listener - we publish transforms from the camera frame to the head pose and from the head pose to the eye gaze for each subject
- Or subscribe to the /subjects/gaze topic where a [MSG_GazeList](https://github.com/Tobias-Fischer/rt_gene/blob/dea26ee5882340fb54202002c450f16c1b85cf59/rt_gene/msg/MSG_GazeList.msg) is published, which in turn contains [MSG_Gaze](https://github.com/Tobias-Fischer/rt_gene/blob/dea26ee5882340fb54202002c450f16c1b85cf59/rt_gene/msg/MSG_Gaze.msg) messages (phi+theta of the eye gaze). Similarly on /subjects/headpose we publish the head poses for the various subjects (see https://github.com/Tobias-Fischer/rt_gene/tree/dea26ee5882340fb54202002c450f16c1b85cf59/rt_gene/msg for the messages used there).
